# Generated by Django 3.1.2 on 2020-10-27 20:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=10, default=Decimal('53.1219648000000006504706107079982757568359375'), max_digits=13)),
                ('latitude', models.DecimalField(decimal_places=10, default=Decimal('18.00025289999999955625753500498831272125244140625'), max_digits=13)),
                ('product', models.CharField(choices=[('PIZZA', 'pizza'), ('SOUP', 'soup'), ('FRIES', 'fries'), ('BURGER', 'burger')], max_length=6)),
                ('queue_positon', models.IntegerField()),
                ('date_order', models.DateField()),
            ],
        ),
    ]
