# Generated by Django 3.1.2 on 2020-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='queue_positon',
            field=models.IntegerField(default=0),
        ),
    ]
