# Generated by Django 3.1.2 on 2020-10-27 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20201027_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
