# Generated by Django 3.1.2 on 2020-10-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_order_date_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='positon',
            field=models.IntegerField(default=2),
        ),
    ]
