# Generated by Django 3.1.2 on 2020-10-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_order_positon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='positon',
        ),
    ]
