# Generated by Django 3.1.2 on 2020-10-28 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_remove_order_positon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wait_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 0, 16, 13, 893221, tzinfo=utc), verbose_name=datetime.datetime(2020, 10, 29, 0, 16, 13, 893221, tzinfo=utc)),
        ),
    ]
