# Generated by Django 3.1.2 on 2020-10-28 00:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_order_wait_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='wait_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 0, 44, 51, 588407, tzinfo=utc)),
        ),
    ]
