# Generated by Django 3.1.2 on 2020-10-28 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20201028_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(default='bydgoszcz', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='wait_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 20, 24, 4, 888239, tzinfo=utc)),
        ),
    ]
