# Generated by Django 3.1.2 on 2020-10-28 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_auto_20201028_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='order',
            name='wait_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 21, 6, 31, 558731, tzinfo=utc)),
        ),
    ]
