# Generated by Django 3.1.2 on 2020-11-08 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_auto_20201028_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='destination',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='order',
            name='wait_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 14, 15, 51, 458194, tzinfo=utc)),
        ),
    ]
