# Generated by Django 3.1.2 on 2020-11-08 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20201108_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='wait_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
